image: doomseeker/doomseeker-build:latest

pipelines:
  default:
    - parallel:
      - step:
          name: Qt4 build
          script:
            - mkdir -p build_qt4
            - cd build_qt4
            - cmake -DFORCE_QT4=true ..
            - make -j$(nproc)
            - make install
      - step:
          name: Qt5 build
          script:
            - mkdir -p build_qt5
            - cd build_qt5
            - cmake ..
            - make -j$(nproc)
            - make install
