image: doomseeker/doomseeker-build:latest

pipelines:
  default:
    - step:
        script:
          - mkdir -p build
          - cd build
          - cmake ..
          - make -j$(nproc)
          - make install
